// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateApiKeyRes interface {
	createApiKeyRes()
}

type CreateDeviceRes interface {
	createDeviceRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteApiKeyRes interface {
	deleteApiKeyRes()
}

type DeleteDeviceRes interface {
	deleteDeviceRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GoogleAuthCallbackRes interface {
	googleAuthCallbackRes()
}

type GoogleAuthStartRes interface {
	googleAuthStartRes()
}

type GoogleAuthSyncRes interface {
	googleAuthSyncRes()
}

type ListApiKeyRes interface {
	listApiKeyRes()
}

type ListDeviceRes interface {
	listDeviceRes()
}

type ListGroupRes interface {
	listGroupRes()
}

type ListGroupUsersRes interface {
	listGroupUsersRes()
}

type ListUserDevicesRes interface {
	listUserDevicesRes()
}

type ListUserKeysRes interface {
	listUserKeysRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadApiKeyRes interface {
	readApiKeyRes()
}

type ReadApiKeyUserRes interface {
	readApiKeyUserRes()
}

type ReadDeviceRes interface {
	readDeviceRes()
}

type ReadDeviceUserRes interface {
	readDeviceUserRes()
}

type ReadGroupRes interface {
	readGroupRes()
}

type ReadUserGroupRes interface {
	readUserGroupRes()
}

type ReadUserRes interface {
	readUserRes()
}

type StatusRes interface {
	statusRes()
}

type UpdateDeviceRes interface {
	updateDeviceRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UserpassLoginRes interface {
	userpassLoginRes()
}
