/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyList
 */
export interface ApiKeyList {
    /**
     * 
     * @type {number}
     * @memberof ApiKeyList
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyList
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiKeyList
     */
    scopes: Array<ApiKeyListScopesEnum>;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyList
     */
    userId: string;
}


/**
 * @export
 */
export const ApiKeyListScopesEnum = {
    User: 'user.*',
    Admin: 'admin.*'
} as const;
export type ApiKeyListScopesEnum = typeof ApiKeyListScopesEnum[keyof typeof ApiKeyListScopesEnum];


/**
 * Check if a given object implements the ApiKeyList interface.
 */
export function instanceOfApiKeyList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "scopes" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ApiKeyListFromJSON(json: any): ApiKeyList {
    return ApiKeyListFromJSONTyped(json, false);
}

export function ApiKeyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'scopes': json['scopes'],
        'userId': json['user_id'],
    };
}

export function ApiKeyListToJSON(value?: ApiKeyList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'scopes': value.scopes,
        'user_id': value.userId,
    };
}

