/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceCreate
 */
export interface DeviceCreate {
    /**
     * 
     * @type {number}
     * @memberof DeviceCreate
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    publicKey: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    presharedKey: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCreate
     */
    allowedIps: string;
}

/**
 * Check if a given object implements the DeviceCreate interface.
 */
export function instanceOfDeviceCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "publicKey" in value;
    isInstance = isInstance && "presharedKey" in value;
    isInstance = isInstance && "endpoint" in value;
    isInstance = isInstance && "allowedIps" in value;

    return isInstance;
}

export function DeviceCreateFromJSON(json: any): DeviceCreate {
    return DeviceCreateFromJSONTyped(json, false);
}

export function DeviceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': json['type'],
        'publicKey': json['public_key'],
        'presharedKey': json['preshared_key'],
        'endpoint': json['endpoint'],
        'allowedIps': json['allowed_ips'],
    };
}

export function DeviceCreateToJSON(value?: DeviceCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'public_key': value.publicKey,
        'preshared_key': value.presharedKey,
        'endpoint': value.endpoint,
        'allowed_ips': value.allowedIps,
    };
}

