/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Status200Response
 */
export interface Status200Response {
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    photoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    lastname?: string;
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof Status200Response
     */
    group?: string;
}

/**
 * Check if a given object implements the Status200Response interface.
 */
export function instanceOfStatus200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Status200ResponseFromJSON(json: any): Status200Response {
    return Status200ResponseFromJSONTyped(json, false);
}

export function Status200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'photoUrl': !exists(json, 'photo_url') ? undefined : json['photo_url'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'lastname': !exists(json, 'lastname') ? undefined : json['lastname'],
        'firstname': !exists(json, 'firstname') ? undefined : json['firstname'],
        'group': !exists(json, 'group') ? undefined : json['group'],
    };
}

export function Status200ResponseToJSON(value?: Status200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'photo_url': value.photoUrl,
        'provider': value.provider,
        'email': value.email,
        'lastname': value.lastname,
        'firstname': value.firstname,
        'group': value.group,
    };
}

